/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.openapigenerator.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.example.openapigenerator.models.Bird
import com.example.openapigenerator.models.Animal

class BirdTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Bird
        //val modelInstance = Bird()

        // to test the property `wingspan`
        should("test wingspan") {
            // uncomment below to test the property
            //modelInstance.wingspan shouldBe ("TODO")
        }

    }
}
